# 세팅하기

## 기본환경

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.decomposition import PCA

In [3]:
# 한글 폰트 지정
import matplotlib.font_manager as fm

font_path = '/Users/mn/Desktop/finalproject/font_final/nanum-barun-gothic/NanumBarunGothic.ttf'  # 경로 확인 필요
fontprop = fm.FontProperties(fname=font_path)

plt.rc('font', family=fontprop.get_name())

In [4]:
print("폰트 이름:", fontprop.get_name())  # 꼭 확인

폰트 이름: NanumBarunGothic

In [5]:
# 컬럼 모두 출력
pd.set_option('display.max_columns', None)

In [6]:
# 현재 작업 디렉토리 출력
wd = os.getcwd()
wd

'/Users/mn/Desktop/finalproject/final_project_team3'

# 빅쿼리 테이블 가져오기

In [7]:
import pandas as pd
from google.oauth2 import service_account

JSON_KEY_PATH = '/Users/mn/Desktop/finalproject/final_project_team3/key/my-projectcodeit.json'
PROJECT_ID = 'my-projectcodeit'
LOCATION = 'asia-northeast3'

# 서비스 계정 키 파일을 사용하여 인증 객체 생성
credentials = service_account.Credentials.from_service_account_file(JSON_KEY_PATH)

In [8]:
# 빅쿼리 데이터 읽기

total_user_df = pd.read_gbq(
    query="SELECT * FROM final_project.total_user_df",
    project_id=PROJECT_ID,
    location=LOCATION,
    credentials=credentials
)
total_user_df.head()

/var/folders/2v/mtvgzsyj7t904n0q0zp_35l80000gn/T/ipykernel_22591/236348846.py:3: FutureWarning: read_gbq is deprecated and will be removed in a future version. Please use pandas_gbq.read_gbq instead: https://pandas-gbq.readthedocs.io/en/latest/api.html#pandas_gbq.read_gbq
  total_user_df = pd.read_gbq(

,user_id,gender,point,is_push_on,created_at,ban_status,report_count,alarm_count,pending_chat,pending_votes,friend_count,block_user_count,hide_user_id_count,attendance_date_count,student_count,school_grade,pointuse_cnt,pointget_cnt,vote_cnt,chosen_cnt,event_cnt,buy_cnt,buyfail_cnt,friendreport_cnt,province
0,1005961,F,2884,1,2023-05-08 11:36:21.504116,N,0,1,0,3,79,0,2,2,239.0,H_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,충청북도
1,1138991,F,226,1,2023-05-11 13:59:12.348719,N,0,0,0,1,44,0,0,0,239.0,H_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,충청북도
2,1151280,F,1920,1,2023-05-11 22:53:47.019996,N,0,1,0,138,25,1,0,1,239.0,H_1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,충청북도
3,1155721,F,1948,1,2023-05-12 02:30:02.890229,N,0,1,0,75,43,0,0,0,239.0,H_1,0.0,0.0,0.0,61.0,0.0,0.0,0.0,0.0,충청북도
4,1158283,F,554,1,2023-05-12 04:59:41.499122,N,0,1,0,44,18,0,0,0,239.0,H_1,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,충청북도

## EDA

In [9]:
total_user_df.describe()

,user_id,point,is_push_on,created_at,report_count,alarm_count,pending_chat,pending_votes,friend_count,block_user_count,hide_user_id_count,attendance_date_count,student_count,pointuse_cnt,pointget_cnt,vote_cnt,chosen_cnt,event_cnt,buy_cnt,buyfail_cnt,friendreport_cnt
count,676984.0,676984.0,676984.0,676984,676984.0,676984.0,676984.0,676984.0,676984.0,676984.0,676984.0,676984.0,676984.000000,676984.000000,676984.000000,676984.000000,676984.000000,676984.000000,676984.000000,676984.000000,676984.000000
mean,1212975.203845,3023.273608,0.843114,2023-05-15 22:43:51.258469,0.036234,0.85077,0.073152,84.639966,53.332367,0.028555,0.764776,3.28241,206.807210,0.160392,3.294517,1.798503,1.798503,0.000451,0.140508,0.000241,0.000307
min,833024.0,0.0,0.0,2023-03-31 09:05:51.903699,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1028100.5,400.0,1.0,2023-05-09 01:39:06.982078,0.0,0.0,0.0,2.0,31.0,0.0,0.0,0.0,136.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1211733.5,965.0,1.0,2023-05-13 10:51:02.905848,0.0,1.0,0.0,29.0,49.0,0.0,0.0,0.0,199.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,1397889.25,2183.0,1.0,2023-05-20 07:48:20.079588,0.0,1.0,0.0,122.0,70.0,0.0,0.0,4.0,272.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1583733.0,885000006.0,1.0,2024-05-09 08:31:17.710824,60.0,238.0,256.0,3352.0,1373.0,178.0,3557.0,310.0,578.000000,343.000000,2955.000000,2786.000000,1239.000000,1.000000,60.000000,2.000000,19.000000
std,213872.756317,1076031.50434,0.363693,NaN,0.363341,0.84534,0.645081,123.267691,32.225902,0.447571,13.936459,7.307541,97.383712,3.088226,47.261928,28.704991,23.071258,0.021221,0.647237,0.015798,0.036983

pending_chat 음수값 발견

In [10]:
total_user_df.shape

(676984, 25)

In [11]:
total_user_df.isnull().sum()

user_id                  0
gender                   0
point                    0
is_push_on               0
created_at               0
ban_status               0
report_count             0
alarm_count              0
pending_chat             0
pending_votes            0
friend_count             0
block_user_count         0
hide_user_id_count       0
attendance_date_count    0
student_count            0
school_grade             0
pointuse_cnt             0
pointget_cnt             0
vote_cnt                 0
chosen_cnt               0
event_cnt                0
buy_cnt                  0
buyfail_cnt              0
friendreport_cnt         0
province                 0
dtype: int64

In [12]:
total_user_df.duplicated().sum()

np.int64(0)

# 클러스터링(PCA 적용)

In [15]:
total_user_df.drop(
    total_user_df[total_user_df['vote_cnt'] == 2786].index,
    inplace=True)

total_user_df.drop(
    total_user_df[total_user_df['pending_chat'] < 0].index,
    inplace=True)

total_user_df.drop(
    total_user_df[total_user_df['ban_status'] == 'W'].index,
    inplace=True)

total_user_df.drop(
    total_user_df[total_user_df['friend_count'] == 0].index,
    inplace=True)


# 활동 유저
active_users = total_user_df[
    (total_user_df['vote_cnt'] != 0) | 
    (total_user_df['chosen_cnt'] != 0) | 
    (total_user_df['attendance_date_count'] != 0)]

# 비활동 유저
inactive_users = total_user_df[
    (total_user_df['vote_cnt'] == 0) &
    (total_user_df['chosen_cnt'] == 0) &
    (total_user_df['attendance_date_count'] == 0)]

data_cluster = active_users.copy()[['attendance_date_count', 
                                    'pending_chat', 'friend_count', 
                                    'vote_cnt', 'buy_cnt', 'chosen_cnt', 
                                    'pointuse_cnt', 'ban_status']]

# 인코딩
df_encoded = pd.get_dummies(data_cluster, columns=['ban_status'], drop_first=False)

# 로그화
df_log = np.log1p(df_encoded) 

# 표준화
ss = StandardScaler()
data_standardized = ss.fit_transform(df_log)

X = pd.DataFrame(data_standardized, columns=df_log.columns)

# pca
pca = PCA(n_components=3)
principal_components = pca.fit_transform(X)
pca_df = pd.DataFrame(principal_components, columns=['PC1', 'PC2', 'PC3'])

# k-means
pca_kmeans = KMeans(n_clusters=3, random_state=123)
pca_kmeans.fit(pca_df)

# 클러스터 결과 할당
active_users_df = active_users.copy()
active_users_df.loc[:, 'Cluster'] = pca_kmeans.predict(pca_df)

# k-means(PCA)
from sklearn.metrics import silhouette_score
silhouette_kmeans = silhouette_score(pca_df, active_users_df['Cluster'])
print(f'Silhouette Score (k-means_PCA): {silhouette_kmeans:.4f}')

Silhouette Score (k-means_PCA): 0.5188

In [16]:
print(total_user_df.shape)
print(active_users.shape)
print(inactive_users.shape)

(666626, 25)
(333636, 25)
(332990, 25)

In [17]:
cluster_final = active_users_df[['attendance_date_count', 
                                    'pending_chat', 'friend_count', 
                                    'vote_cnt', 'buy_cnt', 'chosen_cnt', 
                                    'pointuse_cnt', 'Cluster']]

cluster_result = cluster_final.groupby('Cluster').mean()
cluster_result['COUNT'] = cluster_final['Cluster'].value_counts()
cluster_result.reset_index()

,Cluster,attendance_date_count,pending_chat,friend_count,vote_cnt,buy_cnt,chosen_cnt,pointuse_cnt,COUNT
0,0,4.429941,0.009842,48.727864,0.024996,0.016327,0.702763,0.000495,230234
1,1,11.78732,0.312389,77.202999,0.006707,0.651880,0.218224,0.000000,98848
2,2,2.529864,0.059508,62.775801,262.902723,0.138999,225.113746,23.540843,4554