## 0. 세팅하기

### 기본환경

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os
import duckdb as dd
import dotenv

In [2]:
# 한글 폰트 지정
import matplotlib.font_manager as fm

font_path = '/home/sprintda07/fonts/truetype/nanum/NanumBarunGothic.ttf'  # 경로 확인 필요
fontprop = fm.FontProperties(fname=font_path)

plt.rc('font', family=fontprop.get_name())

In [3]:
# 컬럼 모두 출력
pd.set_option('display.max_columns', None)

In [4]:
# 현재 작업 디렉토리 출력
wd = os.getcwd()
wd

'/home/sprintda07/project4/final_project_team3'

In [5]:
# 절대 경로 (수정해서 사용)
JSON_KEY_PATH = "key/my-projectcodeit.json"

In [ ]:
# DuckDB 연결
env_path = dotenv.find_dotenv()

dotenv.load_dotenv(
    dotenv_path=env_path,
    override=True
)

mem_con = dd.connect("mydb.duckdb")

HMAC_ID = os.getenv("HMAC_ID")
HMAC_PW = os.getenv("HMAC_PW")

secret_gcs = f"""
CREATE SECRET (
    TYPE GCS,
    KEY_ID '{HMAC_ID}',
    SECRET '{HMAC_PW}'
);
"""

mem_con.execute(secret_gcs)
mem_con.execute("FROM duckdb_secrets()").df()

True

### 데이터 불러오기

In [9]:
attendance_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_attendance.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [10]:
blockrecord_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_blockrecord.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [11]:
failpaymenthistory_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_failpaymenthistory.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [12]:
friendrequest_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_friendrequest.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [13]:
group_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_group.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [14]:
nearbyschool_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_nearbyschool.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [15]:
paymenthistory_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_paymenthistory.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [16]:
pointhistory_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_pointhistory.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [17]:
school_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_school.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [18]:
timelinereport_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_timelinereport.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [19]:
contacts_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_user_contacts.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [20]:
userquestionrecord_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_userquestionrecord.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [21]:
userwithdraw_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_userwithdraw.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [22]:
event_receipts_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/event_receipts.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [23]:
events_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/events.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [24]:
user_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_user.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [25]:
polls_question_df = pd.read_parquet(
                                      "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/polls_question.parquet",
                                      engine='pyarrow',
                                      storage_options={'token' : JSON_KEY_PATH}
                                  )

In [26]:
polls_questionpiece_df = pd.read_parquet(
                                      "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/polls_questionpiece.parquet",
                                      engine='pyarrow',
                                      storage_options={'token' : JSON_KEY_PATH}
                                  )

In [27]:
polls_questionreport_df = pd.read_parquet(
                                      "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/polls_questionreport.parquet",
                                      engine='pyarrow',
                                      storage_options={'token' : JSON_KEY_PATH}
                                  )

In [28]:
polls_questionset_df = pd.read_parquet(
                                      "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/polls_questionset.parquet",
                                      engine='pyarrow',
                                      storage_options={'token' : JSON_KEY_PATH}
                                  )

In [29]:
polls_usercandidate_df = pd.read_parquet(
                                      "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/polls_usercandidate.parquet",
                                      engine='pyarrow',
                                      storage_options={'token' : JSON_KEY_PATH}
                                  )

# 2. 피쳐 엔지니어링

### 1) 투표 테이블: 투표기록 + 포인트 기록
userquestionrecord_df

In [51]:
len(userquestionrecord_df), len(pointhistory_df)

(1217558, 2338918)

In [52]:
# pointhistory_df 변환
updated_pointhistory_df = (
    pointhistory_df
    .groupby(['created_at', 'user_question_record_id'], as_index=False)
    .agg({
        'id': 'first',         
        'delta_point': 'sum',   
        'user_id': 'first' 
    })
)

print(updated_pointhistory_df.head())

           created_at  user_question_record_id      id  delta_point  user_id
0 2023-04-28 12:27:49                 771777.0  790629            9   849436
1 2023-04-28 12:28:02                 771800.0  790652            9   849436
2 2023-04-28 12:28:09                 771812.0  790664            5   849436
3 2023-04-28 12:28:16                 771828.0  790680           13   849436
4 2023-04-28 12:28:26                 771851.0  790703            5   849436

In [77]:
updated_pointhistory_df = updated_pointhistory_df.sort_values("created_at")
userquestionrecord_df = userquestionrecord_df.sort_values("created_at")

In [ ]:
# chosen_user_id에 merge
df_with_chosen = userquestionrecord_df.merge(
    updated_pointhistory_df, 
    left_on=["id", "chosen_user_id",], 
    right_on=["user_question_record_id", "user_id",], 
    how="left", 
    suffixes=["", "_point"]
)

df_with_chosen["time_diff"] = (df_with_chosen["created_at_point"] - df_with_chosen["created_at"]).abs()

df_with_chosen = df_with_chosen[df_with_chosen["time_diff"] <= pd.Timedelta("1d")]

final_chosen_df = df_with_chosen.loc[df_with_chosen.groupby("id")["time_diff"].idxmin()]

In [ ]:
# user_id에 merge
df_with_chose = userquestionrecord_df.merge(
    updated_pointhistory_df, 
    left_on=["id", "user_id"], 
    right_on=["user_question_record_id", "user_id"], 
    how="left", 
    suffixes=["", "_point"]
)

df_with_chose["time_diff"] = (df_with_chose["created_at_point"] - df_with_chose["created_at"]).abs()

df_with_chose = df_with_chose[df_with_chose["time_diff"] <= pd.Timedelta("1d")]

final_chose_df = df_with_chose.loc[df_with_chose.groupby("id")["time_diff"].idxmin()]

In [ ]:
# 최종 데이터프레임 생성
df_merged = pd.concat([final_chosen_df, final_chose_df], axis=0)
df_merged

,id,status,created_at,chosen_user_id,question_id,user_id,question_piece_id,has_read,answer_status,answer_updated_at,report_count,opened_times,created_at_point,user_question_record_id,id_point,delta_point,user_id_point,time_diff
34,772123,I,2023-04-28 12:30:48,849489,209,849452,999059,0,N,2023-04-28 12:30:48,0,1,2023-04-28 17:28:06,772123.0,829075.0,-300.0,849489.0,0 days 04:57:18
118,772628,I,2023-04-28 12:34:17,849436,253,849477,998774,0,N,2023-04-28 12:34:17,0,1,2023-04-29 02:27:33,772628.0,849680.0,-300.0,849436.0,0 days 13:53:16
173,773997,I,2023-04-28 12:41:45,849479,117,849566,999684,0,N,2023-04-28 12:41:45,0,1,2023-04-28 14:31:21,773997.0,808783.0,-300.0,849479.0,0 days 01:49:36
201,774559,I,2023-04-28 12:46:14,849503,110,849558,1003854,1,N,2023-04-28 12:46:14,0,1,2023-04-29 10:25:00,774559.0,926292.0,-300.0,849503.0,0 days 21:38:46
355,778695,I,2023-04-28 13:18:14,849983,210,850039,1010379,0,N,2023-04-28 13:18:14,0,1,2023-04-28 15:41:47,778695.0,819109.0,-300.0,849983.0,0 days 02:23:33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1217714,161666166,C,2024-05-07 11:29:07,945560,2614,1001607,190864020,1,N,2024-05-07 11:29:07,0,0,2024-05-07 11:29:07,161666166.0,340671667.0,16.0,NaN,0 days 00:00:00
1217715,161666461,C,2024-05-08 01:34:56,850774,1679,855525,200139931,0,N,2024-05-08 01:34:56,0,0,2024-05-08 01:34:56,161666461.0,340672368.0,10.0,NaN,0 days 00:00:00
1217716,161666462,C,2024-05-08 01:35:02,855509,2605,855525,200139932,0,N,2024-05-08 01:35:02,0,0,2024-05-08 01:35:02,161666462.0,340672370.0,28.0,NaN,0 days 00:00:00
1217717,161666463,C,2024-05-08 01:36:00,855526,3801,855525,200139933,0,N,2024-05-08 01:36:00,0,0,2024-05-08 01:36:00,161666463.0,340672372.0,22.0,NaN,0 days 00:00:00
1217718,161666464,C,2024-05-08 01:36:18,874566,3117,855525,200139934,0,N,2024-05-08 01:36:18,0,0,2024-05-08 01:36:18,161666464.0,340672374.0,24.0,NaN,0 days 00:00:00

In [ ]:
# 중복 제거
df_merged.drop_duplicates(subset=['id'], inplace=True)

In [74]:
updated_pointhistory_df[updated_pointhistory_df["user_question_record_id"].eq(771940)]

,created_at,user_question_record_id,id,delta_point,user_id
10,2023-04-28 12:29:13,771940.0,790793,14,849436
214445,2023-05-07 04:40:33,771940.0,9583599,-300,849634

In [83]:
userquestionrecord_df[userquestionrecord_df["id"].eq(771940)]

,id,status,created_at,chosen_user_id,question_id,user_id,question_piece_id,has_read,answer_status,answer_updated_at,report_count,opened_times
10,771940,I,2023-04-28 12:29:13,849634,297,849436,998465,1,N,2023-04-28 12:29:13,0,1

In [82]:
df_merged[df_merged["id"].eq(771940)]

,id,status,created_at,chosen_user_id,question_id,user_id,question_piece_id,has_read,answer_status,answer_updated_at,report_count,opened_times,created_at_point,user_question_record_id,id_point,delta_point,user_id_point,time_diff
10,771940,I,2023-04-28 12:29:13,849634,297,849436,998465,1,N,2023-04-28 12:29:13,0,1,2023-04-28 12:29:13,771940.0,790793.0,14.0,NaN,0 days

In [ ]:
# DuckDB에 올리기 전 데이터 타입 변환
df_merged["time_diff"] = df_merged["time_diff"].dt.total_seconds()

In [ ]:
# DuckDB에 데이터프레임 저장
mem_con.execute("""
    COPY df_merged TO 'gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/vote_point_df.parquet' (FORMAT PARQUET);
""")

In [ ]:
# pandas로 GCS에 데이터 저장
# def write_data_to_gcs(df, JSON_KEY_PATH, DATASET_PATH, file_name):
#     df.to_parquet(
#         path=f'{DATASET_PATH}/{file_name}.parquet',
#         engine='pyarrow',
#         compression='gzip',
#         index=False,
#         storage_options={'token' : JSON_KEY_PATH}
#     )
# write_data_to_gcs(df_merged, JSON_KEY_PATH, "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes", "vote_point_df")