## 0. 세팅하기

### 기본환경

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import os

In [3]:
# 한글 폰트 지정
import matplotlib.font_manager as fm

import os

font_path = '/usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf'  # 경로 확인 필요
if os.path.exists(font_path):
	fontprop = fm.FontProperties(fname=font_path)
	plt.rc('font', family=fontprop.get_name())
else:
	print(f"Warning: Font file not found at {font_path}. Using default font.")

Warning: Font file not found at /usr/share/fonts/truetype/nanum/NanumBarunGothic.ttf. Using default font.

In [4]:
# 컬럼 모두 출력
pd.set_option('display.max_columns', None)

In [5]:
# 현재 작업 디렉토리 출력
wd = os.getcwd()
wd

'/Users/aaron/Desktop/codeit project/data/git/final_project_team3'

In [18]:
import os
os.environ['GOOGLE_APPLICATION_CREDENTIALS'] = "/Users/aaron/Desktop/codeit project/data/git/my-projectcodeit-fd54d11263b8.json"

In [16]:
# 절대 경로 (수정해서 사용)
JSON_KEY_PATH = "my-projectcodeit-fd54d11263b8.json"

### 데이터 불러오기

In [20]:
attendance_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_attendance.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

_request out of retries on exception: Invalid Credentials, 401
Traceback (most recent call last):
  File "/Users/aaron/Desktop/codeit project/data/parquet/hackle/.venv/lib/python3.13/site-packages/gcsfs/retry.py", line 135, in retry_request
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron/Desktop/codeit project/data/parquet/hackle/.venv/lib/python3.13/site-packages/gcsfs/core.py", line 476, in _request
    validate_response(status, contents, path, args)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aaron/Desktop/codeit project/data/parquet/hackle/.venv/lib/python3.13/site-packages/gcsfs/retry.py", line 122, in validate_response
    raise HttpError(error)
gcsfs.retry.HttpError: Invalid Credentials, 401

HttpError: Invalid Credentials, 401

In [ ]:
blockrecord_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_blockrecord.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
failpaymenthistory_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_failpaymenthistory.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
friendrequest_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_friendrequest.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
group_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_group.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
nearbyschool_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_nearbyschool.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
paymenthistory_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_paymenthistory.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
pointhistory_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_pointhistory.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
school_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_school.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
timelinereport_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_timelinereport.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
contacts_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_user_contacts.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
userquestionrecord_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_userquestionrecord.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
userwithdraw_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_userwithdraw.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
event_receipts_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/event_receipts.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
events_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/events.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
user_df = pd.read_parquet(
                            "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/accounts_user.parquet",
                            engine='pyarrow',
                            storage_options={'token' : JSON_KEY_PATH}
                        )

In [ ]:
polls_question_df = pd.read_parquet(
                                      "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/polls_question.parquet",
                                      engine='pyarrow',
                                      storage_options={'token' : JSON_KEY_PATH}
                                  )

In [ ]:
polls_questionpiece_df = pd.read_parquet(
                                      "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/polls_questionpiece.parquet",
                                      engine='pyarrow',
                                      storage_options={'token' : JSON_KEY_PATH}
                                  )

In [ ]:
polls_questionreport_df = pd.read_parquet(
                                      "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/polls_questionreport.parquet",
                                      engine='pyarrow',
                                      storage_options={'token' : JSON_KEY_PATH}
                                  )

In [ ]:
polls_questionset_df = pd.read_parquet(
                                      "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/polls_questionset.parquet",
                                      engine='pyarrow',
                                      storage_options={'token' : JSON_KEY_PATH}
                                  )

In [ ]:
polls_usercandidate_df = pd.read_parquet(
                                      "gs://sprintda07-gohee-bucket/final_project/최종프로젝트_데이터(parquet)/votes/polls_usercandidate.parquet",
                                      engine='pyarrow',
                                      storage_options={'token' : JSON_KEY_PATH}
                                  )

## 1. 전처리

### 1) user_df

In [ ]:
user_df.head(3)

,id,is_superuser,is_staff,gender,point,friend_id_list,is_push_on,created_at,block_user_id_list,hide_user_id_list,ban_status,report_count,alarm_count,pending_chat,pending_votes,group_id
0,831956,1,1,None,600,"[1292473, 913158, 1488461, 1064695, 1043565, 1...",0,2023-03-29 03:44:14.047130,[],[],N,0,0,0,0,NaN
1,831962,0,0,F,2248,"[833025, 832642, 982531, 879496, 838541, 83752...",1,2023-03-29 05:18:56.162368,[],[],N,253,40878,5499,110,12.0
2,832151,0,0,M,1519,"[838785, 982531, 882567, 879496, 838541, 83649...",0,2023-03-29 12:56:34.989468,[],[],N,0,37,0,47,1.0

### 2) blockrecord_df

In [ ]:
blockrecord_df.head()

   id              reason          created_at  block_user_id  user_id
0   1               그냥... 2023-05-04 23:01:53         867483   878476
1   2         친구 사이가 어색해짐 2023-05-05 01:17:08         867190   867564
2   3  나랑 관련 없는 질문을 자꾸 보냄 2023-05-05 01:50:55         875110   875261
3   6               그냥... 2023-05-05 05:21:52         883696   883511
4   7               그냥... 2023-05-05 06:40:34         871349   870177

### 3) friendrequest_df

In [ ]:
friendrequest_df.head()

,id,status,created_at,updated_at,receive_user_id,send_user_id
0,7,P,2023-04-17 18:29:11,2023-04-17 18:29:11,831962,837521
1,10,A,2023-04-17 18:29:11,2023-04-22 06:02:53,832151,837521
2,11,A,2023-04-17 18:29:11,2023-04-18 19:28:41,832340,837521
3,13,A,2023-04-17 18:29:11,2023-04-19 11:05:04,833041,837521
4,20,P,2023-04-17 18:29:11,2023-04-17 18:29:11,834415,837521

### 4) group_df

In [ ]:
group_df.head()

   id  grade  class_num  school_id
0   1      1          1          1
1   8      3          2          1
2   9      3          3          1
3  10      2          2          1
4  11      2          3          1

### 5) school_df

In [ ]:
school_df.head()

   id   address  student_count school_type
0   4  충청북도 충주시            239           H
1   5  충청북도 충주시            160           M
2   6  충청북도 충주시            200           H
3   7  충청북도 충주시            114           H
4   8  충청북도 충주시            139           M

### 6) nearbyschool_df

In [ ]:
nearbyschool_df.head()

       id  distance  nearby_school_id  school_id
0  119021  0.004564                 6          7
1  119022  0.010787                13          7
2  119023  0.012928                20          7
3  119024  0.013590                 4          7
4  119025  0.014122                24          7

### 7) attendance_df

In [ ]:
attendance_df.head()

   id                               attendance_date_list  user_id
0   1  ["2023-05-27", "2023-05-28", "2023-05-29", "20...  1446852
1   2  ["2023-05-27", "2023-05-29", "2023-05-30", "20...  1359398
2   3  ["2023-05-27", "2023-05-29", "2023-05-30", "20...  1501542
3   4  ["2023-05-27", "2023-05-28", "2023-05-29", "20...  1507767
4   5  ["2023-05-27", "2023-05-28", "2023-05-29", "20...  1287453

### 8) contacts_df

In [ ]:
contacts_df.head()

      id  contacts_count invite_user_id_list  user_id
0    259              30                  []  1167696
1   1756              79                  []   863169
2  13742              21            [854615]   857205
3  13754              29                  []   851431
4  13756              28            [849318]   855476

### 9) userquestionrecord_df

In [ ]:
userquestionrecord_df.head()

,id,status,created_at,chosen_user_id,question_id,user_id,question_piece_id,has_read,answer_status,answer_updated_at,report_count,opened_times
0,771777,C,2023-04-28 12:27:49,849469,252,849436,998458,0,N,2023-04-28 12:27:49,0,0
1,771800,C,2023-04-28 12:28:02,849446,244,849436,998459,0,N,2023-04-28 12:28:02,0,0
2,771812,C,2023-04-28 12:28:09,849454,183,849436,998460,1,N,2023-04-28 12:28:09,0,0
3,771828,C,2023-04-28 12:28:16,847375,101,849436,998461,0,N,2023-04-28 12:28:16,0,0
4,771851,C,2023-04-28 12:28:26,849477,209,849436,998462,1,N,2023-04-28 12:28:26,0,0

### 10) userwithdraw_df

In [ ]:
userwithdraw_df.head()

   id        reason          created_at
0  42   재밌는 질문이 없어서 2023-03-29 13:22:12
1  43  함께 할 친구가 없어서 2023-03-29 13:24:59
2  44  함께 할 친구가 없어서 2023-03-29 13:53:32
3  45  함께 할 친구가 없어서 2023-03-29 13:54:03
4  46   재밌는 질문이 없어서 2023-03-30 00:31:19

### 11) timelinereport_df

In [ ]:
timelinereport_df.head()

,id,reason,created_at,reported_user_id,user_id,user_question_record_id
0,28,타인을 사칭함,2023-05-06 04:44:57,874587,885082,3920588
1,37,친구를 비하하거나 조롱하는 어투,2023-05-06 05:41:19,881048,881298,4018679
2,46,친구를 비하하거나 조롱하는 어투,2023-05-06 06:26:59,887882,881945,4120914
3,64,허위 사실 언급,2023-05-06 07:07:46,888610,893684,4143049
4,65,허위 사실 언급,2023-05-06 07:07:52,888610,893684,4143049

### 12) pointhistory_df

In [ ]:
pointhistory_df.head()

       id  delta_point          created_at  user_id  user_question_record_id
0  790629            9 2023-04-28 12:27:49   849436                 771777.0
1  790652            9 2023-04-28 12:28:02   849436                 771800.0
2  790664            5 2023-04-28 12:28:09   849436                 771812.0
3  790680           13 2023-04-28 12:28:16   849436                 771828.0
4  790703            5 2023-04-28 12:28:26   849436                 771851.0

### 13) failpaymenthistory_df

In [ ]:
failpaymenthistory_df.head()

   id   productId phone_type          created_at  user_id
0   6   heart.200          A 2023-05-14 05:49:22  1055891
1   7   heart.777          A 2023-05-14 08:17:21  1152151
2   8   heart.777          A 2023-05-14 10:11:46   986200
3   9  heart.1000          A 2023-05-14 11:53:09  1028261
4  10   heart.777          A 2023-05-14 12:30:47  1235730

### 14) paymenthistory_df

In [ ]:
paymenthistory_df.head()

   id  productId phone_type          created_at  user_id
0   6  heart.777          A 2023-05-13 21:28:34  1211127
1   7  heart.777          A 2023-05-13 21:29:39  1151343
2   8  heart.777          A 2023-05-13 21:31:33  1002147
3   9  heart.777          A 2023-05-13 21:31:39  1095040
4  11  heart.777          A 2023-05-13 21:34:32  1164081

### 15) event_receipts_df

In [ ]:
event_receipts_df.head()

   id          created_at  event_id  user_id  plus_point
0   2 2023-06-22 09:25:16         1  1193618         500
1   3 2023-06-22 09:38:53         1   928351         500
2   4 2023-06-22 10:32:15         1   904872         500
3   5 2023-06-22 13:03:06         1   974697         500
4   6 2023-06-22 13:40:38         1  1168260         500

### 16) events_df

In [ ]:
events_df.head()

   id           title  plus_point event_type  is_expired          created_at
0   1   코드잇 은행 가입 이벤트         500       FCFS           1 2023-06-20 11:56:38
1   2  코드잇 멤버십 가입 이벤트        1000       FCFS           1 2023-08-08 07:43:45
2   3   예고 영상 기대평 이벤트         500       FCFS           1 2023-09-24 17:05:59

### 17) polls_question_df

In [ ]:
polls_question_df.head()

    id                 question_text          created_at
0   99            가장 신비한 매력이 있는 사람은? 2023-03-31 15:22:53
1  100  "이 사람으로 한 번 살아보고 싶다" 하는 사람은? 2023-03-31 15:22:53
2  101                     미래의 틱톡커는? 2023-03-31 15:22:54
3  102               여기서 제일 특이한 친구는? 2023-03-31 15:22:54
4  103               가장 지켜주고 싶은 사람은? 2023-03-31 15:22:55

### 18) polls_questionpiece_df

In [ ]:
polls_questionpiece_df.head()

       id  is_voted          created_at  question_id  is_skipped
0  998458         1 2023-04-28 12:27:22          252           0
1  998459         1 2023-04-28 12:27:22          244           0
2  998460         1 2023-04-28 12:27:22          183           0
3  998461         1 2023-04-28 12:27:22          101           0
4  998462         1 2023-04-28 12:27:22          209           0

### 19) polls_questionreport_df

In [ ]:
polls_questionreport_df.head()

   id                reason          created_at  question_id  user_id
0   1           이 질문은 재미없어요 2023-04-19 06:20:35          250   837556
1   2           이 질문은 재미없어요 2023-04-19 06:58:09          113   837672
2   3       불쾌한 내용이 포함되어 있음 2023-04-19 06:58:17          113   837672
3   4  어떻게 이런 생각을? 이 질문 최고! 2023-04-19 08:12:42          119   837922
4   5  어떻게 이런 생각을? 이 질문 최고! 2023-04-19 08:12:50          119   837922

### 20) polls_questionset_df

In [ ]:
polls_questionset_df.head()

,id,question_piece_id_list,opening_time,status,created_at,user_id
0,99817,"[998458, 998459, 998460, 998461, 998462, 99846...",2023-04-28 12:27:22,F,2023-04-28 12:27:23,849436
1,99830,"[998588, 998589, 998590, 998591, 998592, 99859...",2023-04-28 12:28:07,F,2023-04-28 12:28:07,849438
2,99840,"[998689, 998691, 998693, 998695, 998697, 99869...",2023-04-28 12:28:38,F,2023-04-28 12:28:38,847375
3,99841,"[998688, 998690, 998692, 998694, 998696, 99869...",2023-04-28 12:28:38,F,2023-04-28 12:28:38,849446
4,99848,"[998768, 998769, 998770, 998771, 998772, 99877...",2023-04-28 12:28:57,F,2023-04-28 12:28:57,849477

### 21) polls_usercandidate_df

In [ ]:
polls_usercandidate_df.head()

        id          created_at  question_piece_id  user_id
0  3088872 2023-04-28 12:27:49             998458   849444
1  3088873 2023-04-28 12:27:49             998458   849454
2  3088874 2023-04-28 12:27:49             998458   849460
3  3088875 2023-04-28 12:27:49             998458   849469
4  3088964 2023-04-28 12:28:02             998459   849446